@echo off
echo Stopping any existing Node.js processes...
taskkill /F /IM node.exe
echo.
echo Starting the server...
start "" /D "%~dp0" /MIN "Node.js Server" cmd /c "npm run start:server"
echo Server is starting in a new window...
